### ISSUE TITLE
Missing instructions for MacOS -> Windows cross compilation

### ISSUE THREAD

**Issue by woelper** [BenjaminRi/winresource#10]
Hi, and thanks for this great library!

I have added a [PR](https://github.com/BenjaminRi/winresource/pull/9) to include setup instructions and sample code.

**Comment by BenjaminRi** [comment]
Thank you for the feedback. I've just added the missing instructions:

https://github.com/BenjaminRi/winresource/commit/b8343f340a91beba214eae9f7a2032680e3b5cb9
