### ISSUE TITLE
Incompatible linking modifiers `+bundle` and `+whole-archive`

### ISSUE THREAD

**Issue by ChristophB** [BenjaminRi/winresource#7]
**rustc version:** rustc 1.66.1 (90743e729 2023-01-10)
**winresource version:** 0.1.14

I get the following error when I cross compile from Debian 11:
**"error: the linking modifiers `+bundle` and `+whole-archive` are not compatible with each other when generating rlibs"**

Changing https://github.com/BenjaminRi/winresource/blob/a40147171f046e2d107d56b1c8b2ece9888abe61/lib.rs#L650 to:

```rs
println!("cargo:rustc-link-lib=static:-bundle,+whole-archive=resource");
```

resolves this issue. But i don't know if this breaks builds with previous rustc versions...

---

Example `build.rs`:
```rs
// build.rs

fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").unwrap() == "windows"
        && std::env::var("PROFILE").unwrap() == "release"
    {
        let mut res = winresource::WindowsResource::new();

        res.set_icon("assets/favicon.ico")
            .set("ProductName", "some name")
            .set("CompanyName", "some company")
            .set("ProductVersion", "0.1.0")
            .set("FileVersion", "0.1.0.0")
            .set("FileDescription", "some description")
            .set("LegalCopyright", "Copyright © Example")
            .compile()
            .unwrap();
    }
}
```

**Comment by BenjaminRi** [comment]
Interesting. I cannot reproduce it on Ubuntu 22.04 LTS.

```
beni@mainpc:~/rust/example/target/x86_64-pc-windows-gnu/debug$ rustc --version
rustc 1.66.1 (90743e729 2023-01-10)
beni@mainpc:~/rust/example/target/x86_64-pc-windows-gnu/debug$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

I'll have to look into docker / a VM to see what's up with this.

**Comment by ChristophB** [comment]
It seems that my project setup was a bit messed up (I'm still a rust newby). I had a `src/lib.rs` next to my `src/main.rs`. After removing the `src/lib.rs`, cross compilation worked!

Sorry to have bothered you with this issue.

**Comment by BenjaminRi** [comment]
> After removing the `src/lib.rs`, cross compilation worked!

Oh, that could explain things. A resource can only be applied to a binary, not a library.

> Sorry to have bothered you with this issue.

No problem.
